// DTC Report PDF — exports the current DTC scan as a printable report.
// Uses the browser's print-to-PDF so no external dependencies are needed.

function esc(s) {
  return String(s).replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c]));
}

function buildReportHtml(vin, dtcs) {
  const rows = dtcs.map(d => `
    <tr>
      <td>${esc(d.ecu || '—')}</td>
      <td>${esc(d.code)}</td>
      <td>${esc(d.description || '')}</td>
      <td>${esc(d.status || '')}</td>
    </tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Beemuu DTC Report — ${esc(vin)}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #111; }
  h1 { font-size: 20px; } .meta { color: #555; margin-bottom: 24px; }
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid #999; padding: 6px 10px; text-align: left; font-size: 13px; }
  th { background: #eee; }
  footer { margin-top: 32px; font-size: 11px; color: #777; }
</style></head><body>
<h1>Diagnostic Trouble Code Report</h1>
<div class="meta">
  VIN: <strong>${esc(vin)}</strong><br>
  Generated: ${new Date().toISOString()}<br>
  Total DTCs: ${dtcs.length}
</div>
<table><thead><tr><th>ECU</th><th>Code</th><th>Description</th><th>Status</th></tr></thead>
<tbody>${rows || '<tr><td colspan="4">No trouble codes found.</td></tr>'}</tbody></table>
<footer>Generated by Beemuu + DTC Report PDF plugin (open-source, GPL-3.0).</footer>
</body></html>`;
}

export async function activate(context) {
  context.ui.registerPanel({
    title: 'DTC Report',
    render(container) {
      const btn = document.createElement('button');
      btn.textContent = 'Export DTC report (PDF)';
      btn.style.cssText = 'padding:10px 18px;font-size:14px;cursor:pointer;';
      btn.onclick = async () => {
        btn.disabled = true;
        btn.textContent = 'Scanning…';
        try {
          const [vin, dtcs] = await Promise.all([
            context.vehicle.readVin(),
            context.vehicle.readDtc()
          ]);
          const w = window.open('', '_blank');
          w.document.write(buildReportHtml(vin, dtcs));
          w.document.close();
          w.focus();
          w.print(); // user picks "Save as PDF"
          context.ui.notify('Report generated — choose "Save as PDF" in the print dialog.');
        } catch (err) {
          context.ui.notify('Report failed: ' + err.message);
        } finally {
          btn.disabled = false;
          btn.textContent = 'Export DTC report (PDF)';
        }
      };
      container.appendChild(btn);
    }
  });
}

export function deactivate() {}
